language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install xlrd
  
before_script:
  - pip install pytest

script:
  - pytest test.py

notifications:
  email: false


deploy:
  provider: pypi
  user: Williamzjc
  password: Python2017
  on:
    python: 3.8
    tags: true
    branch: master
