language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
    - pip install git+https://github.com/pytoolz/.git

before_script:
  - pip install pandas numpy nltk
  - pip install pypinyin

script:
  - source test.sh


install:
    - python setup.py build_ext --inplace --with-cython
    - pip install -e .

# commands to run tests
script:
    - nosetests --with-doctest cytoolz
    # For convenience, make sure simple test commands work
    - py.test
    - nosetests
    # Make sure we can cimport cytoolz
    - echo 'cimport cytoolz ; from cytoolz.functoolz cimport memoize' > try_cimport_cytoolz.pyx
    - cythonize -i try_cimport_cytoolz.pyx
    - python -c 'import try_cimport_cytoolz'

notifications:
  email: false
